repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.1.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-json
      - id: debug-statements
      - id: detect-private-key
  - repo: https://github.com/pre-commit/mirrors-eslint
    rev: "v8.22.0" # Use the sha / tag you want to point at
    hooks:
      - id: eslint
        args: [--fix]
        files: \.[jt]sx?$ # *.js, *.jsx, *.ts and *.tsx
        types: [file]
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: "v2.7.1" # Use the sha / tag you want to point at
    hooks:
      - id: prettier
