// export const API_BASE_URL = process.env.NEXT_PUBLIC_SERVER_BASE_URL;
//  export const API_BASE_URL = "https://api.admizz.com";
export const API_BASE_URL ="http://localhost:3005"

export const GLOBAL_ERROR = "GLOBAL_ERROR";
export const SUCCESS = "SUCCESS";
//blog
export const BLOGS_TYPES = {
  GET_BLOGS: "GET_BLOGS",
  GET_BLOGS_INIT: "GET_BLOGS_INIT",
  GET_BLOGS_FINISH: "GET_BLOGS_FINISH",
};

//faq

export const FAQ_TYPES = {
  GET_FAQS: "GET_FAQS",
  GET_FAQ: "GET_FAQ",
  UPDATE_FAQ: "UPDATE_FAQ",
  DELETE_FAQ: "DELETE_FAQ",
  CREATE_FAQ: "CREATE_FAQ"
};
//Gallery
export const GALLERY_TYPES ={
GET_GALLERY:"GET_GALLERY",
GET_GALLERY_INIT:"GET_GALLERY_INIT",
GET_GALLERY_FINISH:"GET_GALLERY_FINISH"
};

export const BLOG_TYPES = {
  GET_BLOG: "GET_BLOG",
  GET_BLOG_INIT: "GET_BLOG_INIT",
  GET_BLOG_FINISH: "GET_BLOG_FINISH",
};

export const GET_COLLEGE_NEWS = "GET_COLLEGE_NEWS";

// favourites
export const FAVOURITES = {
  USER_FAVOURITES: "USER_FAVORITES",
  ADD_TO_FAVOURITES: "ADD_TO_FAVOURITES",
  REMOVE_FAVOURITES: "REMOVE_FAVOURITES",
};

//Comments
export const COMMENT_TYPES = {
  ADD_COMMENT:"ADD_COMMENT",
  GET_COMMENT:"GET_COMMENT",
  GET_COMMENT_INIT:"GET_COMMENT_INIT",
  GET_COMMENT_FINISH:"GET_COMMENT_FINISH"
}
//testimonial
export const TESTIMONIAL_TYPES = {
  GET_TESTIMONIAL:"GET_TESTIMONIAL",
  GET_ALL_TESTIMONIAL:"GET_ALL_TESTIMONIAL",
  GET_YEAR_LIST:"GET_YEAR_LIST",
  GET_TESTIMONIAL_INIT:"GET_TESTIMONIAL_INIT",
  GET_TESTIMONIAL_FINISH:"GET_TESTIMONIAL_FINISH",
  GET_STUDENT_TESTIMONIAL:"GET_STUDENT_TESTIMONIAL",
  GET_UNIVERSITY_TESTIMONIAL:"GET_UNIVERSITY_TESTIMONIAL"
}
//college
export const COLLEGES_TYPES = {
  GET_COLLEGES: "GET_COLLEGES",
  GET_COMPARE_LIST:" GET_COMPARE_LIST",
  GET_COLLEGES_INIT: "GET_COLLEGES_INIT",
  GET_COLLEGES_FINISH: "GET_COLLEGES_FINISH",
};

export const COLLEGE_TYPES = {
  GET_COLLEGE: "GET_COLLEGE",
  GET_COLLEGE_INIT: "GET_COLLEGE_INIT",
  GET_COLLEGE_FINISH: "GET_COLLEGE_FINISH",
};

export const GET_COLLAGE_DETAIL = "GET_COLLAGE_DETAIL";
export const GET_ALL_BLOG = "GET_ALL_BLOG";
export const GET_Blog_Detail = "GET_Blog_Detail";
export const GET_ALL_COLLAGE = "GET_ALL_COLLAGE";

//user
export const GET_AUTH_USER = "GET_AUTH_USER";

//application
export const GET_APPLICATION = "GET_APPLICATION";
export const UPDATE_APPLICATION = "UPDATE_APPLICATION";
//Gallery
export const GET_ALL_GALLERY ="GET_ALL_GALLERY";

//courses
export const GET_LEVELS = "GET_LEVELS";
export const GET_STREAMS = "GET_STREAMS";
export const GET_PROGRAMS = "GET_PROGRAMS";
export const GET_CHOICE_COLLEGES = "GET_CHOICE_COLLEGES";

//filterList
export const GET_COUNTY_LIST_BEGIN = "GET_COUNTY_LIST_BEGIN";
export const GET_COUNTRY_LIST = "GET_COUNTRY_LIST";
export const GET_COURSE_LEVEL_LIST_BEGIN = "GET_COURSE_LEVEL_LIST_BEGIN";
export const GET_COURSE_LEVEL_LIST = "GET_COURSE_LEVEL_LIST";
export const GET_STATE_LIST_BEGIN = "GET_STATE_LIST_BEGIN";
export const GET_STATE_LIST = "GET_STATE_LIST";
export const GET_CITY_LIST_BEGIN = "GET_CITY_LIST_BEGIN";
export const GET_CITY_LIST = "GET_CITY_LIST";
export const GET_COURSE_LEVEL = "GET_COURSE_LEVEL";
export const GET_PROGRAM_NAME = "GET_PROGRAM_NAME";

//college by limit
export const COLLEGE_BY_LIMIT_BEGIN = "COLLEGE_BY_LIMIT_BEGIN";
export const COLLEGE_BY_LIMIT = "COLLEGE_BY_LIMIT";
export const TOTAL_COLLEGE = "TOTAL_COLLEGE";
export const COLLEGE_BY_FILTER = "COLLEGE_BY_FILTER";
export const COLLEGE_BY_SEARCH = "COLLEGE_BY_SEARCH";
export const COLLEGE_BY_LIMIT_FAILED = "COLLEGE_BY_LIMIT_FAILED";

export const GET_TOP_COLLEGES_TYPES = {
  TOP_COLLEGES_BEGIN: "TOP_COLLEGES_BEGIN",
  ADD_TOP_COLLEGES: "ADD_TOP_COLLEGES",
  GET_TOP_COLLEGES: "GET_TOP_COLLEGES",
};

export const GET_TOP_COURSES_TYPES = {
  TOP_COURSES_BEGIN: "TOP_COURSES_BEGIN",
  ADD_TOP_COURSES: "ADD_TOP_COURSES",
  GET_TOP_COURSES: "GET_TOP_COURSES",
};
//FAQ
export const GET_FAQ_TYPES = {
  FAQ_BEGIN: "FAQ_BEGIN",
  FAQ_GET: "FAQ_GET",
  FAQ_ADD: "FAQ_ADD",
  FAQ_END: "FAQ_END",
  FAQ_ID:"FAQ_ID"
};
