const TestimonialArray = [
  {
    name: "susmita khanal",
    img: "profile.jpg",
    place: "Nepal",
    batch: "2069",
    course: "BE",
    subject: "BIM",
  },
  {
    name: "Asmita Adikari",
    img: "profile.jpg",
    place: "Nepal",
    batch: "2059",
    course: "BE",
    subject: "MSC",
  },
  {
    name: "Solanki Shrestha",
    img: "profile.jpg",
    place: "Nepal",
    batch: "2010",
    course: "BE",
    subject: "Computer Engineering",
  },
  {
    name: "Asmita Stha",
    img: "profile.jpg",
    place: "Nepal",
    batch: "2011",
    course: "BE",
    subject: "MSC",
  },
  {
    name: "Shaibya",
    img: "profile.jpg",
    place: "Nepal",
    batch: "2022",
    course: "BE",
    subject: "MSC",
  },
  {
    name: "Shyama",
    img: "profile.jpg",
    place: "Nepal",
    batch: "2069",
    course: "BE",
    subject: "MSC",
  },
  {
    name: "Dipin Pradhan",
    img: "profile.jpg",
    place: "Nepal",
    batch: "2069",
    course: "BE",
    subject: "management",
  },
  {
    name: "Nitisha",
    img: "profile.jpg",
    place: "Nepal",
    batch: "2069",
    course: "BE",
    subject: "BIT",
  },
  {
    name: "Rojan Dhimal",
    img: "profile.jpg",
    place: "Nepal",
    batch: "2069",
    course: "BE",
    subject: "CSIT",
  },
];
export default TestimonialArray;
